title: Ftt2333's Nest
menu: 
  - name: Friends
    links:
      - name: Enucai
        link: https://enucai.github.io/
        avatar: https://cdn.luogu.com.cn/upload/usericon/169574.png
      - name: Cmk666
        link: https://cmk666.github.io/
        avatar: https://cdn.luogu.com.cn/upload/usericon/127949.png
      - name: Cyb1010
        link: https://cyb1010.github.io/
        avatar: https://cdn.luogu.com.cn/upload/usericon/333119.png
      - name: Rbtree
        link: https://red-black-tree.github.io/
        avatar: https://cdn.luogu.com.cn/upload/usericon/173951.png
  - name: Archives 
    link: /archives/
  - name: Categories 
    link: /categories/
  - name: Tags
    link: /tags/
twikoo:
  enable: false
  envId: https://twikoo.netlify.app/
valine:
  enable: false
  serverURL: https://p8sdao2e.api.lncldglobal.com
  appID: P8sDao2EqFI5YSHHRgZRUlcf-MdYXbMMI
  appKey: HfV1waxmQBjSpsTMI5Ca3mVt
waline:
  enable: false
  serverURL: 
cusdis:
  enable: false
  appId: 820d338c-bf94-43ff-bed9-abc1a00b6cf1
changyan:
  enable: false
  appId: cywST4ykv
  conf: prod_67b4a42514e189ad97b4ef392b35a67e